[package]
name = "vrg"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28.6"
raw-window-handle = "0.5"
ash = { version = "0.37.3", default-features = false, features = ["linked", "debug"] }
ash-window = { version = "0.12.0" }
vk-mem = "0.4.0"